# constants operate from the bottom-right, to the top-left.
BOTTOM_INPUTLINE_POS = 2
INPUTLINE_BORDER1_POS = BOTTOM_INPUTLINE_POS + 1
INPUTLINE_BORDER2_POS = INPUTLINE_BORDER1_POS + 1
BOTTOM_HUDLINE_POS = INPUTLINE_BORDER2_POS + 1
CURSOR_POS = BOTTOM_HUDLINE_POS - 1
TEXTCHAT_END_POS = BOTTOM_HUDLINE_POS + 1

INPUT_LINE_AMT = 2

# How far to cut off input text to the right
INPUT_LINE_RIGHT_CUTOFF_POS = 1